# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kn/rpc/fin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kn/rpc/fin.proto',
  package='kn.fin',
  syntax='proto3',
  serialized_pb=_b('\n\x10kn/rpc/fin.proto\x12\x06kn.fin\"\x14\n\x04Year\x12\x0c\n\x04year\x18\x01 \x01(\x05\"E\n\x0c\x41\x63\x63ountQuery\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12\x14\n\x0c\x61\x63\x63ount_type\x18\x03 \x01(\t\"\x0e\n\x0c\x44\x65\x62itorQuery\"\x0b\n\tYearQuery\":\n\x0cGnucashQuery\x12\x1a\n\x04year\x18\x01 \x01(\x0b\x32\x0c.kn.fin.Year\x12\x0e\n\x06handle\x18\x02 \x01(\t\"(\n\nErrorQuery\x12\x1a\n\x04year\x18\x01 \x01(\x0b\x32\x0c.kn.fin.Year\"\x16\n\x05Names\x12\r\n\x05names\x18\x01 \x03(\t\"\t\n\x07\x41\x63\x63ount\"\n\n\x08\x44\x65\x62itors\"X\n\x0eGnucashObjects\x12\x35\n\x07objects\x18\x01 \x03(\x0b\x32$.kn.fin.GnucashObjects.GnucashObject\x1a\x0f\n\rGnucashObject\"$\n\x05Years\x12\x1b\n\x05years\x18\x01 \x03(\x0b\x32\x0c.kn.fin.Year\"\xd9\x02\n\x12\x43heckNamesResponse\x12\x38\n\x07gnucash\x18\x01 \x03(\x0b\x32\'.kn.fin.CheckNamesResponse.GnucashEntry\x12\x38\n\x07website\x18\x02 \x03(\x0b\x32\'.kn.fin.CheckNamesResponse.WebsiteEntry\x1a\x1d\n\x0cMissingUsers\x12\r\n\x05users\x18\x01 \x03(\t\x1aW\n\x0cGnucashEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.kn.fin.CheckNamesResponse.MissingUsers:\x02\x38\x01\x1aW\n\x0cWebsiteEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x36\n\x05value\x18\x02 \x01(\x0b\x32\'.kn.fin.CheckNamesResponse.MissingUsers:\x02\x38\x01\"\xb7\x01\n\x06\x45rrors\x12\'\n\x06\x63hecks\x18\x01 \x03(\x0b\x32\x17.kn.fin.Errors.FinCheck\x1a\x83\x01\n\x08\x46inCheck\x12,\n\x05\x63heck\x18\x01 \x01(\x0b\x32\x1d.kn.fin.Errors.FinCheck.Check\x12\x0f\n\x07objects\x18\x02 \x03(\t\x1a\x38\n\x05\x43heck\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\tb\x06proto3')
)




_YEAR = _descriptor.Descriptor(
  name='Year',
  full_name='kn.fin.Year',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='kn.fin.Year.year', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=48,
)


_ACCOUNTQUERY = _descriptor.Descriptor(
  name='AccountQuery',
  full_name='kn.fin.AccountQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.fin.AccountQuery.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='kn.fin.AccountQuery.full_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='account_type', full_name='kn.fin.AccountQuery.account_type', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=119,
)


_DEBITORQUERY = _descriptor.Descriptor(
  name='DebitorQuery',
  full_name='kn.fin.DebitorQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=121,
  serialized_end=135,
)


_YEARQUERY = _descriptor.Descriptor(
  name='YearQuery',
  full_name='kn.fin.YearQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=137,
  serialized_end=148,
)


_GNUCASHQUERY = _descriptor.Descriptor(
  name='GnucashQuery',
  full_name='kn.fin.GnucashQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='kn.fin.GnucashQuery.year', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='handle', full_name='kn.fin.GnucashQuery.handle', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=208,
)


_ERRORQUERY = _descriptor.Descriptor(
  name='ErrorQuery',
  full_name='kn.fin.ErrorQuery',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='year', full_name='kn.fin.ErrorQuery.year', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=250,
)


_NAMES = _descriptor.Descriptor(
  name='Names',
  full_name='kn.fin.Names',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='names', full_name='kn.fin.Names.names', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=252,
  serialized_end=274,
)


_ACCOUNT = _descriptor.Descriptor(
  name='Account',
  full_name='kn.fin.Account',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=285,
)


_DEBITORS = _descriptor.Descriptor(
  name='Debitors',
  full_name='kn.fin.Debitors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=297,
)


_GNUCASHOBJECTS_GNUCASHOBJECT = _descriptor.Descriptor(
  name='GnucashObject',
  full_name='kn.fin.GnucashObjects.GnucashObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=372,
  serialized_end=387,
)

_GNUCASHOBJECTS = _descriptor.Descriptor(
  name='GnucashObjects',
  full_name='kn.fin.GnucashObjects',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='objects', full_name='kn.fin.GnucashObjects.objects', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_GNUCASHOBJECTS_GNUCASHOBJECT, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=299,
  serialized_end=387,
)


_YEARS = _descriptor.Descriptor(
  name='Years',
  full_name='kn.fin.Years',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='years', full_name='kn.fin.Years.years', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=389,
  serialized_end=425,
)


_CHECKNAMESRESPONSE_MISSINGUSERS = _descriptor.Descriptor(
  name='MissingUsers',
  full_name='kn.fin.CheckNamesResponse.MissingUsers',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='users', full_name='kn.fin.CheckNamesResponse.MissingUsers.users', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=566,
  serialized_end=595,
)

_CHECKNAMESRESPONSE_GNUCASHENTRY = _descriptor.Descriptor(
  name='GnucashEntry',
  full_name='kn.fin.CheckNamesResponse.GnucashEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kn.fin.CheckNamesResponse.GnucashEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kn.fin.CheckNamesResponse.GnucashEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=597,
  serialized_end=684,
)

_CHECKNAMESRESPONSE_WEBSITEENTRY = _descriptor.Descriptor(
  name='WebsiteEntry',
  full_name='kn.fin.CheckNamesResponse.WebsiteEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kn.fin.CheckNamesResponse.WebsiteEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kn.fin.CheckNamesResponse.WebsiteEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=686,
  serialized_end=773,
)

_CHECKNAMESRESPONSE = _descriptor.Descriptor(
  name='CheckNamesResponse',
  full_name='kn.fin.CheckNamesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gnucash', full_name='kn.fin.CheckNamesResponse.gnucash', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='website', full_name='kn.fin.CheckNamesResponse.website', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_CHECKNAMESRESPONSE_MISSINGUSERS, _CHECKNAMESRESPONSE_GNUCASHENTRY, _CHECKNAMESRESPONSE_WEBSITEENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=773,
)


_ERRORS_FINCHECK_CHECK = _descriptor.Descriptor(
  name='Check',
  full_name='kn.fin.Errors.FinCheck.Check',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.fin.Errors.FinCheck.Check.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='kn.fin.Errors.FinCheck.Check.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='kn.fin.Errors.FinCheck.Check.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=903,
  serialized_end=959,
)

_ERRORS_FINCHECK = _descriptor.Descriptor(
  name='FinCheck',
  full_name='kn.fin.Errors.FinCheck',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='check', full_name='kn.fin.Errors.FinCheck.check', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='objects', full_name='kn.fin.Errors.FinCheck.objects', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ERRORS_FINCHECK_CHECK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=828,
  serialized_end=959,
)

_ERRORS = _descriptor.Descriptor(
  name='Errors',
  full_name='kn.fin.Errors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='checks', full_name='kn.fin.Errors.checks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ERRORS_FINCHECK, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=776,
  serialized_end=959,
)

_GNUCASHQUERY.fields_by_name['year'].message_type = _YEAR
_ERRORQUERY.fields_by_name['year'].message_type = _YEAR
_GNUCASHOBJECTS_GNUCASHOBJECT.containing_type = _GNUCASHOBJECTS
_GNUCASHOBJECTS.fields_by_name['objects'].message_type = _GNUCASHOBJECTS_GNUCASHOBJECT
_YEARS.fields_by_name['years'].message_type = _YEAR
_CHECKNAMESRESPONSE_MISSINGUSERS.containing_type = _CHECKNAMESRESPONSE
_CHECKNAMESRESPONSE_GNUCASHENTRY.fields_by_name['value'].message_type = _CHECKNAMESRESPONSE_MISSINGUSERS
_CHECKNAMESRESPONSE_GNUCASHENTRY.containing_type = _CHECKNAMESRESPONSE
_CHECKNAMESRESPONSE_WEBSITEENTRY.fields_by_name['value'].message_type = _CHECKNAMESRESPONSE_MISSINGUSERS
_CHECKNAMESRESPONSE_WEBSITEENTRY.containing_type = _CHECKNAMESRESPONSE
_CHECKNAMESRESPONSE.fields_by_name['gnucash'].message_type = _CHECKNAMESRESPONSE_GNUCASHENTRY
_CHECKNAMESRESPONSE.fields_by_name['website'].message_type = _CHECKNAMESRESPONSE_WEBSITEENTRY
_ERRORS_FINCHECK_CHECK.containing_type = _ERRORS_FINCHECK
_ERRORS_FINCHECK.fields_by_name['check'].message_type = _ERRORS_FINCHECK_CHECK
_ERRORS_FINCHECK.containing_type = _ERRORS
_ERRORS.fields_by_name['checks'].message_type = _ERRORS_FINCHECK
DESCRIPTOR.message_types_by_name['Year'] = _YEAR
DESCRIPTOR.message_types_by_name['AccountQuery'] = _ACCOUNTQUERY
DESCRIPTOR.message_types_by_name['DebitorQuery'] = _DEBITORQUERY
DESCRIPTOR.message_types_by_name['YearQuery'] = _YEARQUERY
DESCRIPTOR.message_types_by_name['GnucashQuery'] = _GNUCASHQUERY
DESCRIPTOR.message_types_by_name['ErrorQuery'] = _ERRORQUERY
DESCRIPTOR.message_types_by_name['Names'] = _NAMES
DESCRIPTOR.message_types_by_name['Account'] = _ACCOUNT
DESCRIPTOR.message_types_by_name['Debitors'] = _DEBITORS
DESCRIPTOR.message_types_by_name['GnucashObjects'] = _GNUCASHOBJECTS
DESCRIPTOR.message_types_by_name['Years'] = _YEARS
DESCRIPTOR.message_types_by_name['CheckNamesResponse'] = _CHECKNAMESRESPONSE
DESCRIPTOR.message_types_by_name['Errors'] = _ERRORS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Year = _reflection.GeneratedProtocolMessageType('Year', (_message.Message,), dict(
  DESCRIPTOR = _YEAR,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Year)
  ))
_sym_db.RegisterMessage(Year)

AccountQuery = _reflection.GeneratedProtocolMessageType('AccountQuery', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNTQUERY,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.AccountQuery)
  ))
_sym_db.RegisterMessage(AccountQuery)

DebitorQuery = _reflection.GeneratedProtocolMessageType('DebitorQuery', (_message.Message,), dict(
  DESCRIPTOR = _DEBITORQUERY,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.DebitorQuery)
  ))
_sym_db.RegisterMessage(DebitorQuery)

YearQuery = _reflection.GeneratedProtocolMessageType('YearQuery', (_message.Message,), dict(
  DESCRIPTOR = _YEARQUERY,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.YearQuery)
  ))
_sym_db.RegisterMessage(YearQuery)

GnucashQuery = _reflection.GeneratedProtocolMessageType('GnucashQuery', (_message.Message,), dict(
  DESCRIPTOR = _GNUCASHQUERY,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.GnucashQuery)
  ))
_sym_db.RegisterMessage(GnucashQuery)

ErrorQuery = _reflection.GeneratedProtocolMessageType('ErrorQuery', (_message.Message,), dict(
  DESCRIPTOR = _ERRORQUERY,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.ErrorQuery)
  ))
_sym_db.RegisterMessage(ErrorQuery)

Names = _reflection.GeneratedProtocolMessageType('Names', (_message.Message,), dict(
  DESCRIPTOR = _NAMES,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Names)
  ))
_sym_db.RegisterMessage(Names)

Account = _reflection.GeneratedProtocolMessageType('Account', (_message.Message,), dict(
  DESCRIPTOR = _ACCOUNT,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Account)
  ))
_sym_db.RegisterMessage(Account)

Debitors = _reflection.GeneratedProtocolMessageType('Debitors', (_message.Message,), dict(
  DESCRIPTOR = _DEBITORS,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Debitors)
  ))
_sym_db.RegisterMessage(Debitors)

GnucashObjects = _reflection.GeneratedProtocolMessageType('GnucashObjects', (_message.Message,), dict(

  GnucashObject = _reflection.GeneratedProtocolMessageType('GnucashObject', (_message.Message,), dict(
    DESCRIPTOR = _GNUCASHOBJECTS_GNUCASHOBJECT,
    __module__ = 'kn.rpc.fin_pb2'
    # @@protoc_insertion_point(class_scope:kn.fin.GnucashObjects.GnucashObject)
    ))
  ,
  DESCRIPTOR = _GNUCASHOBJECTS,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.GnucashObjects)
  ))
_sym_db.RegisterMessage(GnucashObjects)
_sym_db.RegisterMessage(GnucashObjects.GnucashObject)

Years = _reflection.GeneratedProtocolMessageType('Years', (_message.Message,), dict(
  DESCRIPTOR = _YEARS,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Years)
  ))
_sym_db.RegisterMessage(Years)

CheckNamesResponse = _reflection.GeneratedProtocolMessageType('CheckNamesResponse', (_message.Message,), dict(

  MissingUsers = _reflection.GeneratedProtocolMessageType('MissingUsers', (_message.Message,), dict(
    DESCRIPTOR = _CHECKNAMESRESPONSE_MISSINGUSERS,
    __module__ = 'kn.rpc.fin_pb2'
    # @@protoc_insertion_point(class_scope:kn.fin.CheckNamesResponse.MissingUsers)
    ))
  ,

  GnucashEntry = _reflection.GeneratedProtocolMessageType('GnucashEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHECKNAMESRESPONSE_GNUCASHENTRY,
    __module__ = 'kn.rpc.fin_pb2'
    # @@protoc_insertion_point(class_scope:kn.fin.CheckNamesResponse.GnucashEntry)
    ))
  ,

  WebsiteEntry = _reflection.GeneratedProtocolMessageType('WebsiteEntry', (_message.Message,), dict(
    DESCRIPTOR = _CHECKNAMESRESPONSE_WEBSITEENTRY,
    __module__ = 'kn.rpc.fin_pb2'
    # @@protoc_insertion_point(class_scope:kn.fin.CheckNamesResponse.WebsiteEntry)
    ))
  ,
  DESCRIPTOR = _CHECKNAMESRESPONSE,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.CheckNamesResponse)
  ))
_sym_db.RegisterMessage(CheckNamesResponse)
_sym_db.RegisterMessage(CheckNamesResponse.MissingUsers)
_sym_db.RegisterMessage(CheckNamesResponse.GnucashEntry)
_sym_db.RegisterMessage(CheckNamesResponse.WebsiteEntry)

Errors = _reflection.GeneratedProtocolMessageType('Errors', (_message.Message,), dict(

  FinCheck = _reflection.GeneratedProtocolMessageType('FinCheck', (_message.Message,), dict(

    Check = _reflection.GeneratedProtocolMessageType('Check', (_message.Message,), dict(
      DESCRIPTOR = _ERRORS_FINCHECK_CHECK,
      __module__ = 'kn.rpc.fin_pb2'
      # @@protoc_insertion_point(class_scope:kn.fin.Errors.FinCheck.Check)
      ))
    ,
    DESCRIPTOR = _ERRORS_FINCHECK,
    __module__ = 'kn.rpc.fin_pb2'
    # @@protoc_insertion_point(class_scope:kn.fin.Errors.FinCheck)
    ))
  ,
  DESCRIPTOR = _ERRORS,
  __module__ = 'kn.rpc.fin_pb2'
  # @@protoc_insertion_point(class_scope:kn.fin.Errors)
  ))
_sym_db.RegisterMessage(Errors)
_sym_db.RegisterMessage(Errors.FinCheck)
_sym_db.RegisterMessage(Errors.FinCheck.Check)


_CHECKNAMESRESPONSE_GNUCASHENTRY.has_options = True
_CHECKNAMESRESPONSE_GNUCASHENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_CHECKNAMESRESPONSE_WEBSITEENTRY.has_options = True
_CHECKNAMESRESPONSE_WEBSITEENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
