# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kn/rpc/foto.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kn/rpc/foto.proto',
  package='kn.foto',
  syntax='proto3',
  serialized_pb=_b('\n\x11kn/rpc/foto.proto\x12\x07kn.foto\"Z\n\x08UserDirs\x12\'\n\x04\x64irs\x18\x01 \x03(\x0b\x32\x19.kn.foto.UserDirs.UserDir\x1a%\n\x07UserDir\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\":\n\tFotoEvent\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x11\n\thumanname\x18\x03 \x01(\t\"C\n\x08\x46otoDesc\x12\r\n\x05\x65vent\x18\x01 \x01(\t\x12\r\n\x05store\x18\x02 \x01(\t\x12\x0c\n\x04user\x18\x03 \x01(\t\x12\x0b\n\x03\x64ir\x18\x04 \x01(\tb\x06proto3')
)




_USERDIRS_USERDIR = _descriptor.Descriptor(
  name='UserDir',
  full_name='kn.foto.UserDirs.UserDir',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='path', full_name='kn.foto.UserDirs.UserDir.path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.foto.UserDirs.UserDir.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=83,
  serialized_end=120,
)

_USERDIRS = _descriptor.Descriptor(
  name='UserDirs',
  full_name='kn.foto.UserDirs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='dirs', full_name='kn.foto.UserDirs.dirs', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_USERDIRS_USERDIR, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=120,
)


_FOTOEVENT = _descriptor.Descriptor(
  name='FotoEvent',
  full_name='kn.foto.FotoEvent',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='date', full_name='kn.foto.FotoEvent.date', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.foto.FotoEvent.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humanname', full_name='kn.foto.FotoEvent.humanname', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=180,
)


_FOTODESC = _descriptor.Descriptor(
  name='FotoDesc',
  full_name='kn.foto.FotoDesc',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='event', full_name='kn.foto.FotoDesc.event', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='store', full_name='kn.foto.FotoDesc.store', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='kn.foto.FotoDesc.user', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dir', full_name='kn.foto.FotoDesc.dir', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=249,
)

_USERDIRS_USERDIR.containing_type = _USERDIRS
_USERDIRS.fields_by_name['dirs'].message_type = _USERDIRS_USERDIR
DESCRIPTOR.message_types_by_name['UserDirs'] = _USERDIRS
DESCRIPTOR.message_types_by_name['FotoEvent'] = _FOTOEVENT
DESCRIPTOR.message_types_by_name['FotoDesc'] = _FOTODESC
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

UserDirs = _reflection.GeneratedProtocolMessageType('UserDirs', (_message.Message,), dict(

  UserDir = _reflection.GeneratedProtocolMessageType('UserDir', (_message.Message,), dict(
    DESCRIPTOR = _USERDIRS_USERDIR,
    __module__ = 'kn.rpc.foto_pb2'
    # @@protoc_insertion_point(class_scope:kn.foto.UserDirs.UserDir)
    ))
  ,
  DESCRIPTOR = _USERDIRS,
  __module__ = 'kn.rpc.foto_pb2'
  # @@protoc_insertion_point(class_scope:kn.foto.UserDirs)
  ))
_sym_db.RegisterMessage(UserDirs)
_sym_db.RegisterMessage(UserDirs.UserDir)

FotoEvent = _reflection.GeneratedProtocolMessageType('FotoEvent', (_message.Message,), dict(
  DESCRIPTOR = _FOTOEVENT,
  __module__ = 'kn.rpc.foto_pb2'
  # @@protoc_insertion_point(class_scope:kn.foto.FotoEvent)
  ))
_sym_db.RegisterMessage(FotoEvent)

FotoDesc = _reflection.GeneratedProtocolMessageType('FotoDesc', (_message.Message,), dict(
  DESCRIPTOR = _FOTODESC,
  __module__ = 'kn.rpc.foto_pb2'
  # @@protoc_insertion_point(class_scope:kn.foto.FotoDesc)
  ))
_sym_db.RegisterMessage(FotoDesc)


# @@protoc_insertion_point(module_scope)
