# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kn/rpc/mail.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='kn/rpc/mail.proto',
  package='kn.mail',
  syntax='proto3',
  serialized_pb=_b('\n\x11kn/rpc/mail.proto\x12\x07kn.mail\"\x14\n\x04List\x12\x0c\n\x04name\x18\x01 \x01(\t\"!\n\x0fModeratorCookie\x12\x0e\n\x06\x63ookie\x18\x01 \x01(\t\"-\n\nModeration\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tmoderated\x18\x02 \x01(\x08\"\xba\x01\n\nMembership\x12\x37\n\nmembership\x18\x01 \x03(\x0b\x32#.kn.mail.Membership.MembershipEntry\x1a%\n\x05Lists\x12\x1c\n\x05lists\x18\x01 \x03(\x0b\x32\r.kn.mail.List\x1aL\n\x0fMembershipEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12(\n\x05value\x18\x02 \x01(\x0b\x32\x19.kn.mail.Membership.Lists:\x02\x38\x01\"\xf1\x01\n\x0eModeratedLists\x12\x31\n\x05lists\x18\x01 \x03(\x0b\x32\".kn.mail.ModeratedLists.ListsEntry\x1aW\n\rModeratedList\x12\x0f\n\x07modmode\x18\x01 \x01(\t\x12\x11\n\treal_name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05queue\x18\x04 \x01(\x05\x1aS\n\nListsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x34\n\x05value\x18\x02 \x01(\x0b\x32%.kn.mail.ModeratedLists.ModeratedList:\x02\x38\x01\x62\x06proto3')
)




_LIST = _descriptor.Descriptor(
  name='List',
  full_name='kn.mail.List',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.mail.List.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=50,
)


_MODERATORCOOKIE = _descriptor.Descriptor(
  name='ModeratorCookie',
  full_name='kn.mail.ModeratorCookie',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cookie', full_name='kn.mail.ModeratorCookie.cookie', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=85,
)


_MODERATION = _descriptor.Descriptor(
  name='Moderation',
  full_name='kn.mail.Moderation',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='kn.mail.Moderation.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='moderated', full_name='kn.mail.Moderation.moderated', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=132,
)


_MEMBERSHIP_LISTS = _descriptor.Descriptor(
  name='Lists',
  full_name='kn.mail.Membership.Lists',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lists', full_name='kn.mail.Membership.Lists.lists', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=243,
)

_MEMBERSHIP_MEMBERSHIPENTRY = _descriptor.Descriptor(
  name='MembershipEntry',
  full_name='kn.mail.Membership.MembershipEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kn.mail.Membership.MembershipEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kn.mail.Membership.MembershipEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=245,
  serialized_end=321,
)

_MEMBERSHIP = _descriptor.Descriptor(
  name='Membership',
  full_name='kn.mail.Membership',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='membership', full_name='kn.mail.Membership.membership', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MEMBERSHIP_LISTS, _MEMBERSHIP_MEMBERSHIPENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=135,
  serialized_end=321,
)


_MODERATEDLISTS_MODERATEDLIST = _descriptor.Descriptor(
  name='ModeratedList',
  full_name='kn.mail.ModeratedLists.ModeratedList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modmode', full_name='kn.mail.ModeratedLists.ModeratedList.modmode', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='real_name', full_name='kn.mail.ModeratedLists.ModeratedList.real_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='kn.mail.ModeratedLists.ModeratedList.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='queue', full_name='kn.mail.ModeratedLists.ModeratedList.queue', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=393,
  serialized_end=480,
)

_MODERATEDLISTS_LISTSENTRY = _descriptor.Descriptor(
  name='ListsEntry',
  full_name='kn.mail.ModeratedLists.ListsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='kn.mail.ModeratedLists.ListsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='kn.mail.ModeratedLists.ListsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=482,
  serialized_end=565,
)

_MODERATEDLISTS = _descriptor.Descriptor(
  name='ModeratedLists',
  full_name='kn.mail.ModeratedLists',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='lists', full_name='kn.mail.ModeratedLists.lists', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_MODERATEDLISTS_MODERATEDLIST, _MODERATEDLISTS_LISTSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=324,
  serialized_end=565,
)

_MEMBERSHIP_LISTS.fields_by_name['lists'].message_type = _LIST
_MEMBERSHIP_LISTS.containing_type = _MEMBERSHIP
_MEMBERSHIP_MEMBERSHIPENTRY.fields_by_name['value'].message_type = _MEMBERSHIP_LISTS
_MEMBERSHIP_MEMBERSHIPENTRY.containing_type = _MEMBERSHIP
_MEMBERSHIP.fields_by_name['membership'].message_type = _MEMBERSHIP_MEMBERSHIPENTRY
_MODERATEDLISTS_MODERATEDLIST.containing_type = _MODERATEDLISTS
_MODERATEDLISTS_LISTSENTRY.fields_by_name['value'].message_type = _MODERATEDLISTS_MODERATEDLIST
_MODERATEDLISTS_LISTSENTRY.containing_type = _MODERATEDLISTS
_MODERATEDLISTS.fields_by_name['lists'].message_type = _MODERATEDLISTS_LISTSENTRY
DESCRIPTOR.message_types_by_name['List'] = _LIST
DESCRIPTOR.message_types_by_name['ModeratorCookie'] = _MODERATORCOOKIE
DESCRIPTOR.message_types_by_name['Moderation'] = _MODERATION
DESCRIPTOR.message_types_by_name['Membership'] = _MEMBERSHIP
DESCRIPTOR.message_types_by_name['ModeratedLists'] = _MODERATEDLISTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

List = _reflection.GeneratedProtocolMessageType('List', (_message.Message,), dict(
  DESCRIPTOR = _LIST,
  __module__ = 'kn.rpc.mail_pb2'
  # @@protoc_insertion_point(class_scope:kn.mail.List)
  ))
_sym_db.RegisterMessage(List)

ModeratorCookie = _reflection.GeneratedProtocolMessageType('ModeratorCookie', (_message.Message,), dict(
  DESCRIPTOR = _MODERATORCOOKIE,
  __module__ = 'kn.rpc.mail_pb2'
  # @@protoc_insertion_point(class_scope:kn.mail.ModeratorCookie)
  ))
_sym_db.RegisterMessage(ModeratorCookie)

Moderation = _reflection.GeneratedProtocolMessageType('Moderation', (_message.Message,), dict(
  DESCRIPTOR = _MODERATION,
  __module__ = 'kn.rpc.mail_pb2'
  # @@protoc_insertion_point(class_scope:kn.mail.Moderation)
  ))
_sym_db.RegisterMessage(Moderation)

Membership = _reflection.GeneratedProtocolMessageType('Membership', (_message.Message,), dict(

  Lists = _reflection.GeneratedProtocolMessageType('Lists', (_message.Message,), dict(
    DESCRIPTOR = _MEMBERSHIP_LISTS,
    __module__ = 'kn.rpc.mail_pb2'
    # @@protoc_insertion_point(class_scope:kn.mail.Membership.Lists)
    ))
  ,

  MembershipEntry = _reflection.GeneratedProtocolMessageType('MembershipEntry', (_message.Message,), dict(
    DESCRIPTOR = _MEMBERSHIP_MEMBERSHIPENTRY,
    __module__ = 'kn.rpc.mail_pb2'
    # @@protoc_insertion_point(class_scope:kn.mail.Membership.MembershipEntry)
    ))
  ,
  DESCRIPTOR = _MEMBERSHIP,
  __module__ = 'kn.rpc.mail_pb2'
  # @@protoc_insertion_point(class_scope:kn.mail.Membership)
  ))
_sym_db.RegisterMessage(Membership)
_sym_db.RegisterMessage(Membership.Lists)
_sym_db.RegisterMessage(Membership.MembershipEntry)

ModeratedLists = _reflection.GeneratedProtocolMessageType('ModeratedLists', (_message.Message,), dict(

  ModeratedList = _reflection.GeneratedProtocolMessageType('ModeratedList', (_message.Message,), dict(
    DESCRIPTOR = _MODERATEDLISTS_MODERATEDLIST,
    __module__ = 'kn.rpc.mail_pb2'
    # @@protoc_insertion_point(class_scope:kn.mail.ModeratedLists.ModeratedList)
    ))
  ,

  ListsEntry = _reflection.GeneratedProtocolMessageType('ListsEntry', (_message.Message,), dict(
    DESCRIPTOR = _MODERATEDLISTS_LISTSENTRY,
    __module__ = 'kn.rpc.mail_pb2'
    # @@protoc_insertion_point(class_scope:kn.mail.ModeratedLists.ListsEntry)
    ))
  ,
  DESCRIPTOR = _MODERATEDLISTS,
  __module__ = 'kn.rpc.mail_pb2'
  # @@protoc_insertion_point(class_scope:kn.mail.ModeratedLists)
  ))
_sym_db.RegisterMessage(ModeratedLists)
_sym_db.RegisterMessage(ModeratedLists.ModeratedList)
_sym_db.RegisterMessage(ModeratedLists.ListsEntry)


_MEMBERSHIP_MEMBERSHIPENTRY.has_options = True
_MEMBERSHIP_MEMBERSHIPENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_MODERATEDLISTS_LISTSENTRY.has_options = True
_MODERATEDLISTS_LISTSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
